---
title: ВОО Дети Сталинграда
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: detistalingrada@gmail.com
description: Официальный сайт Волгоградской общественной организации Дкти Сталинграда
baseurl: ''
url: detistalingrada.github.io
theme: minima
plugins:
- jekyll-feed
